const Index = {
    anagramma: { exec: require('../../commands/anagramma'), name: 'Анаграмма' },
    anagramma2: { exec: require('../../commands/anagramma2'), name: 'Анаграмма из 2 слов' },
    association: { exec: require('../../commands/association'), name: 'Ассоциации' },
    associationlogic: { exec: require('../../commands/associationLogic'), name: 'Ассоциации + Логика' },
    azimut: { exec: require('../../commands/azimut'), name: 'Азимут' },
    dick: { exec: require('../../commands/raschlenenka'), name: 'Расчлененка' },
    mask: { exec: require('../../commands/mask'), name: 'Маска' },
    maskword: { exec: require('../../commands/maskWord'), name: 'Маска + слово' },
    phrase: { exec: require('../../commands/frazeologism'), name: 'Фразеологизмы' },
    meta: { exec: require('../../commands/metagramma'), name: 'Метаграммы' },
    morze: { exec: require('../../commands/morze'), name: 'Азбука Морзе' },
    logo: { exec: require('../../commands/logogrif'), name: 'Логогрифы' },
    any: { exec: require('../../commands/any'), name: 'Все форматы' },
    brukva: { exec: require('../../commands/brukva'), name: 'Брюква' },
    matrix: { exec: require('../../commands/matrix'), name: 'Матрицы' },
    subword: { exec: require('../../commands/subword'), name: 'Подслова' },
    longword: { exec: require('../../commands/longword'), name: 'Надслова' },
    alphabet: { exec: require('../../commands/alphabet'), name: 'Цифры по алфавиту' },
    bacon: { exec: require('../../commands/bacon'), name: 'Бэкон' },
    bodo: { exec: require('../../commands/bodo'), name: 'Бодо' },
    binary: { exec: require('../../commands/binary'), name: 'Двоичка' },
    tm: { exec: require('../../commands/mendeleev'), name: 'Таблица Менделеева' },
    rebus: { exec: require('../../commands/rebus'), name: 'Ребусы' },
    list: { exec: require('../../commands/codesList'), name: 'Список кодов' },
    noize: { exec: require('../../commands/noize'), name: 'Noize MC' },
    krug: { exec: require('../../commands/krug'), name: 'Михаил Круг' },
    plus: { exec: require('../../commands/plus'), name: 'Плюсограмма' },
    book: { exec: require('../../commands/book'), name: 'Поиск по книгам' },
    film: { exec: require('../../commands/film'), name: 'Поиск по фильмам' },
    painting: { exec: require('../../commands/painting'), name: 'Поиск по картинам' },
    gapoifika: { exec: require('../../commands/gapoifika'), name: 'ГаПоИФиКа' },
    adjectives: { exec: require('../../commands/adjectives'), name: 'Прилагательные' },
    nouns: { exec: require('../../commands/nouns'), name: 'Существительные' },
    cross: { exec: require('../../commands/cross'), name: 'Общая часть' },
    brail: { exec: require('../../commands/brail'), name: 'Азбука брайля' },
    roman: { exec: require('../../commands/romeNumerals'), name: 'Римские числа' },
    sborka: { exec: require('../../commands/sborka'), name: 'Сборка' },
    sborkaline: { exec: require('../../commands/sborkaLine'), name: 'Сборка 1 строки' },
    ss: { exec: require('../../commands/ss'), name: 'Системы счисления' },
    notes: { exec: require('../../commands/notes'), name: 'Ноты' },
    vigenere: { exec: require('../../commands/vigenere'), name: 'Шифр виженера' },
    caesar: { exec: require('../../commands/caesar'), name: 'Шифр цезаря' },
};

const ALIASES = {
    anagramma: Index.anagramma,
    anagramma2: Index.anagramma2,
    ass: Index.association,
    association: Index.association,
    associationlogic: Index.associationlogic,
    azimut: Index.azimut,
    dick: Index.dick,
    mask: Index.mask,
    maskword: Index.maskword,
    phrase: Index.phrase,
    meta: Index.meta,
    logo: Index.logo,
    morze: Index.morze,
    any: Index.any,
    brukva: Index.brukva,
    matrix: Index.matrix,
    subword: Index.subword,
    longword: Index.longword,
    alf: Index.alphabet,
    bacon: Index.bacon,
    bodo: Index.bodo,
    binary: Index.binary,
    tm: Index.tm,
    rebus: Index.rebus,
    list: Index.list,
    noize: Index.noize,
    krug: Index.krug,
    plus: Index.plus,
    book: Index.book,
    film: Index.film,
    painting: Index.painting,
    gapoifika: Index.gapoifika,
    adj: Index.adjectives,
    noun: Index.nouns,
    cross: Index.cross,
    brail: Index.brail,
    roman: Index.roman,
    sborka: Index.sborka,
    ss: Index.ss,
    notes: Index.notes,
    sborkaline: Index.sborkaline,
    vigenere: Index.vigenere,
    caesar: Index.caesar,
};

module.exports = {Index, ALIASES};
